### ISSUE TITLE
Unable to build when including libraries that rely on c_int, socklen_t, etc.

### ISSUE THREAD

**Issue by effervescentia** [alexcrichton/wasm-bindgen#68]
This may be purely a case of naïveté on my part, I came across the [Mozilla article](https://hacks.mozilla.org/2018/03/making-webassembly-better-for-rust-for-all-languages/) that referenced your library and thought it would be a fun project to set up a rust-wasm bridge to this rust [`unrar` package](https://github.com/muja/unrar.rs) – that itself is a bridge to the C unrar – and compare it in performance to [a similar project created with emscripten](https://github.com/YuJianrong/node-unrar.js). It's been years since I've touched a system-level language and have equally little knowledge about `wasm`, but at the very least I can determine that the source of my headache is purely from including the `unrar` library when compiling to `wasm32-unknown-unknown`. The attached is the full output that I received when attempting to compile to that target with the following setup.

```rust
// src/lib.rs
#![feature(proc_macro)]

extern crate wasm_bindgen;

use wasm_bindgen::prelude::*;

#[wasm_bindgen]
extern {
    fn alert(s: &str);
}

#[wasm_bindgen]
pub fn greet(name: &str) {
    alert(&format!("Hello, {}!", name));
}
```

```toml
# Cargo.toml
[package]
name = "wasm_test"
version = "0.1.0"
authors = ["Ben Teichman <ben.l.teichman@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.1"
unrar = "0.4.3"
```

This was the output I received when running it:

[output.log](https://github.com/alexcrichton/wasm-bindgen/files/1813597/output.log)
